title: Preheat
description: Adaptive readahead daemon for Linux

# Disable GitHub Pages default theme
theme: null

# SASS configuration
sass:
  sass_dir: assets/css
  style: compressed

# Default layout for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
